# Azure build pipelines for Sysmon

resources:
  repositories:
  - repository: Sysmon
    type: github
    endpoint: sysinternals
    name: sysinternals/SysmonforLinux

  - repository: SysinternalsEBPF
    type: github
    endpoint: sysinternals
    name: sysinternals/SysinternalsEBPF

trigger:
    branches:
      include:
        - release/*
        - main
      exclude:
        - dev/*
        - test/*

pr:
- main

stages:
 - stage: "Build"
   jobs:
    - job: "Build_Sysmon_Ubuntu"
      pool:
        name: "Sysinternals-for-Linux-AME"
        demands:
        - ImageOverride -equals sysmon-ubuntu-build-agent
      steps:
      - checkout: self
        submodules: true

      - checkout: SysinternalsEBPF

      - template: templates/build.yaml@SysinternalsEBPF
        parameters:
          srcFolder: 'SysinternalsEBPF'

      - script: |
          cd $(Build.SourcesDirectory)/SysinternalsEBPF/build
          make install
          ldconfig
        displayName: "Install SysinternalsEBPF"

      - template: templates/build.yaml
        parameters:
          srcFolder: 'SysmonForLinux'
