# Azure build pipelines for Sysmon

trigger:
    branches:
      include:
        - release/*
        - main
      exclude:
        - dev/*
        - test/*
  
pr:
- main

jobs:
  - job: "Build_Sysmon"
    pool: "Sysmon-Ubuntu-20.04-Pool"
    steps:
    - script: |
        apt install sysinternalsebpf
        mkdir build && cd build
        cmake ..
        make
        sudo apt remove sysinternalsebpf
      displayName: "Build Sysmon Binary"
  
  - job: "Sysmon_Package_Build"
    pool: "Sysmon-Ubuntu-20.04-Pool"
    condition: not(eq(variables['Build.Reason'], 'PullRequest'))
    dependsOn:
      - "Build_Sysmon"
    steps:
    - script: |
        export REVISION=$(Build.BuildId)
        sed -i "s/999999/$REVISION/g" $(Build.SourcesDirectory)/CMakeLists.txt
        mkdir $(Build.SourcesDirectory)/build && cd $(Build.SourcesDirectory)/build
        cmake ..
        make
      displayName: "Build Sysmon Binary"
    
    - script: |
        mkdir $(Build.SourcesDirectory)/pkgbuild
        cd $(Build.SourcesDirectory)/build
        make packages
        mv deb/*.deb $(Build.SourcesDirectory)/pkgbuild
      displayName: "Build Sysmon Package"
    
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/pkgbuild/'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/Ubuntu/'
      displayName: 'Copy build artifacts to staging'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

# Add centos build
