# Azure build pipelines for Sysmon

resources:
  repositories:
  - repository: Sysmon
    type: github
    endpoint: sysinternals
    name: sysinternals/SysmonforLinux

  - repository: SysinternalsEBPF
    type: github
    endpoint: sysinternals
    name: sysinternals/SysinternalsEBPF

trigger:
    branches:
      include:
        - release/*
        - main
      exclude:
        - dev/*
        - test/*

pr:
- main

stages:
 - stage: "Build"
   jobs:
    - job: "Build_Sysmon_Ubuntu"
      pool:
        vmImage: "ubuntu-20.04"
      timeoutInMinutes: 240
      steps:
      - checkout: self
        submodules: true

      - checkout: SysinternalsEBPF

      - script: |
          ls
          chmod +x SysmonForLinux/.container/install-ubuntu-dependencies.sh
          SysmonForLinux/.container/install-ubuntu-dependencies.sh
        displayName: "Install pre-reqs for Ubuntu"

      - template: templates/build.yaml@SysinternalsEBPF
        parameters:
          srcPath: 'SysinternalsEBPF'
          runStaticAnalysis: false

      - script: |
          cd $(Build.SourcesDirectory)/SysinternalsEBPF/sysinternalsEBPF_build
          make install
          ldconfig
        displayName: "Install SysinternalsEBPF"

      - template: templates/build.yaml
        parameters:
          srcPath: 'SysmonForLinux'
          runStaticAnalysis: true
