# Azure build pipelines for Sysinternalsebpf

trigger:
    branches:
      include:
        - release/*
        - main
      exclude:
        - dev/*
        - test/*
  
pr:
- main

jobs:
  - job: "Build_Sysinternalsebpf"
    pool: "Sysmon-Ubuntu-20.04-Pool"
    steps:
    - script: |
        mkdir build && cd build
        cmake ..
        make
      displayName: "Build Sysinternalsebpf Binary"
  
  - job: "Sysinternalsebpf_Package_Build"
    pool: "Sysmon-Ubuntu-20.04-Pool"
    condition: not(eq(variables['Build.Reason'], 'PullRequest'))
    dependsOn:
      - "Build_Sysinternalsebpf"
    steps:
    - script: |
        export REVISION=$(Build.BuildId)
        sed -i "s/999999/$REVISION/g" $(Build.SourcesDirectory)/CMakeLists.txt
        mkdir $(Build.SourcesDirectory)/build && cd $(Build.SourcesDirectory)/build
        cmake ..
        make
      displayName: "Build Sysinternalsebpf Binary"
    
    - script: |
        mkdir $(Build.SourcesDirectory)/pkgbuild
        cd $(Build.SourcesDirectory)/build
        make packages
        mv deb/*.deb $(Build.SourcesDirectory)/pkgbuild
      displayName: "Build Sysinternalsebpf Package"
    
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/pkgbuild/'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/Ubuntu/'
      displayName: 'Copy build artifacts to staging'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

# Add centos build
